name: CI/CD for SimpleTimeService

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t shrutipp/simple-time:${{ github.sha }} .

    
      - name: Tag Docker image
        run: |
          docker tag shrutipp/simple-time:${{ github.sha }} shrutipp/simple-time:latest

  
      - name: Push Docker image to DockerHub
        run: |
          docker push shrutipp/simple-time:${{ github.sha }}
          docker push shrutipp/simple-time:latest
