apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
      - name: simpletimeservice
        image: shrutipp/simple-time:tagname
        ports:
        - containerPort: 4545
---
apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice
spec:
  selector:
    app: simpletimeservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4545
  type: ClusterIP
