apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
      - name: simpletimeservice
        image: shrutipp/simple-time:latest
        ports:
        - containerPort: 4545
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice
spec:
  selector:
    app: simpletimeservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4545
  type: ClusterIP
